// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.shovelgame.domain.i18n;

import com.shovelgame.domain.i18n.SkillModelDescirption;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SkillModelDescirption_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager SkillModelDescirption.entityManager;
    
    public static final List<String> SkillModelDescirption.fieldNames4OrderClauseFilter = java.util.Arrays.asList("");
    
    public static final EntityManager SkillModelDescirption.entityManager() {
        EntityManager em = new SkillModelDescirption().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long SkillModelDescirption.countSkillModelDescirptions() {
        return entityManager().createQuery("SELECT COUNT(o) FROM SkillModelDescirption o", Long.class).getSingleResult();
    }
    
    public static List<SkillModelDescirption> SkillModelDescirption.findAllSkillModelDescirptions() {
        return entityManager().createQuery("SELECT o FROM SkillModelDescirption o", SkillModelDescirption.class).getResultList();
    }
    
    public static List<SkillModelDescirption> SkillModelDescirption.findAllSkillModelDescirptions(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM SkillModelDescirption o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, SkillModelDescirption.class).getResultList();
    }
    
    public static SkillModelDescirption SkillModelDescirption.findSkillModelDescirption(Long id) {
        if (id == null) return null;
        return entityManager().find(SkillModelDescirption.class, id);
    }
    
    public static List<SkillModelDescirption> SkillModelDescirption.findSkillModelDescirptionEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM SkillModelDescirption o", SkillModelDescirption.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<SkillModelDescirption> SkillModelDescirption.findSkillModelDescirptionEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM SkillModelDescirption o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, SkillModelDescirption.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void SkillModelDescirption.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void SkillModelDescirption.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            SkillModelDescirption attached = SkillModelDescirption.findSkillModelDescirption(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void SkillModelDescirption.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void SkillModelDescirption.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public SkillModelDescirption SkillModelDescirption.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        SkillModelDescirption merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
