// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.shovelgame.game.domain.data;

import org.shovelgame.game.domain.data.RewardClaimPK;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RewardClaimPK_Roo_Configurable {
    
    declare @type: RewardClaimPK: @Configurable;
    
}
