// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.shovelgame.game.domain.data;

import java.io.Serializable;
import org.shovelgame.game.domain.data.RightsPK;

privileged aspect RightsPK_Roo_Serializable {
    
    declare parents: RightsPK implements Serializable;
    
    private static final long RightsPK.serialVersionUID = 1L;
    
}
