// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.shovelgame.game.domain.i18n;

import org.shovelgame.game.domain.i18n.Language;

privileged aspect Language_Roo_JavaBean {
    
    public String Language.getId() {
        return this.id;
    }
    
    public void Language.setId(String id) {
        this.id = id;
    }
    
}
