// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.shovelgame.game.domain.i18n;

import org.shovelgame.game.domain.i18n.SkillDescription;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SkillDescription_Roo_Configurable {
    
    declare @type: SkillDescription: @Configurable;
    
}
