// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.shovelgame.i18n;

import org.shovelgame.i18n.HeroTypeDescription;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect HeroTypeDescription_Roo_Configurable {
    
    declare @type: HeroTypeDescription: @Configurable;
    
}
