// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.shovelgame.domain.model;

import com.shovelgame.domain.model.HeroSkillPK;
import java.io.Serializable;

privileged aspect HeroSkillPK_Roo_Serializable {
    
    declare parents: HeroSkillPK implements Serializable;
    
    private static final long HeroSkillPK.serialVersionUID = 1L;
    
}
