// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.shovelgame.domain.model;

import com.shovelgame.domain.model.MinionTraitPK;
import java.io.Serializable;

privileged aspect MinionTraitPK_Roo_Serializable {
    
    declare parents: MinionTraitPK implements Serializable;
    
    private static final long MinionTraitPK.serialVersionUID = 1L;
    
}
