// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.shovelgame.domain.model;

import com.shovelgame.domain.i18n.SkillModelDescirption;
import com.shovelgame.domain.model.AttributeType;
import com.shovelgame.domain.model.EnchantmentType;
import com.shovelgame.domain.model.HeroSkill;
import com.shovelgame.domain.model.MinionSkill;
import com.shovelgame.domain.model.SkillModel;
import java.math.BigDecimal;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;

privileged aspect SkillModel_Roo_DbManaged {
    
    @OneToMany(mappedBy = "skillModel")
    private Set<SkillModelDescirption> SkillModel.skillModelDescirptions;
    
    @OneToMany(mappedBy = "skillModel")
    private Set<EnchantmentType> SkillModel.enchantmentTypes;
    
    @OneToMany(mappedBy = "skillModel")
    private Set<HeroSkill> SkillModel.heroSkills;
    
    @OneToMany(mappedBy = "skillModel")
    private Set<MinionSkill> SkillModel.minionSkills;
    
    @ManyToOne
    @JoinColumn(name = "attribute_type", referencedColumnName = "id")
    private AttributeType SkillModel.attributeType;
    
    @Column(name = "power", precision = 10, scale = 3)
    private BigDecimal SkillModel.power;
    
    @Column(name = "icon_name", length = 50)
    @NotNull
    private String SkillModel.iconName;
    
    public Set<SkillModelDescirption> SkillModel.getSkillModelDescirptions() {
        return skillModelDescirptions;
    }
    
    public void SkillModel.setSkillModelDescirptions(Set<SkillModelDescirption> skillModelDescirptions) {
        this.skillModelDescirptions = skillModelDescirptions;
    }
    
    public Set<EnchantmentType> SkillModel.getEnchantmentTypes() {
        return enchantmentTypes;
    }
    
    public void SkillModel.setEnchantmentTypes(Set<EnchantmentType> enchantmentTypes) {
        this.enchantmentTypes = enchantmentTypes;
    }
    
    public Set<HeroSkill> SkillModel.getHeroSkills() {
        return heroSkills;
    }
    
    public void SkillModel.setHeroSkills(Set<HeroSkill> heroSkills) {
        this.heroSkills = heroSkills;
    }
    
    public Set<MinionSkill> SkillModel.getMinionSkills() {
        return minionSkills;
    }
    
    public void SkillModel.setMinionSkills(Set<MinionSkill> minionSkills) {
        this.minionSkills = minionSkills;
    }
    
    public AttributeType SkillModel.getAttributeType() {
        return attributeType;
    }
    
    public void SkillModel.setAttributeType(AttributeType attributeType) {
        this.attributeType = attributeType;
    }
    
    public BigDecimal SkillModel.getPower() {
        return power;
    }
    
    public void SkillModel.setPower(BigDecimal power) {
        this.power = power;
    }
    
    public String SkillModel.getIconName() {
        return iconName;
    }
    
    public void SkillModel.setIconName(String iconName) {
        this.iconName = iconName;
    }
    
}
