// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.shovelgame.domain.model;

import com.shovelgame.domain.model.SkillModel;
import com.shovelgame.enumaration.SkillAlgorithm;

privileged aspect SkillModel_Roo_JavaBean {
    
    public SkillAlgorithm SkillModel.getAlg() {
        return this.alg;
    }
    
    public void SkillModel.setAlg(SkillAlgorithm alg) {
        this.alg = alg;
    }
    
}
