// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.shovelgame.game.domain.model.reward;

import org.shovelgame.game.domain.model.reward.GoldReward;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect GoldReward_Roo_Configurable {
    
    declare @type: GoldReward: @Configurable;
    
}
